amc/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('create/', views.AmcCreateView.as_view(), name='amc_create'),
    path('<pk>/update/', views.AmcEditView.as_view(), name='amc_update'),
    path('<pk>/delete/', views.AmcDeleteView.as_view(), name='amc_delete'),

    path('list/', views.get_all_amc, name='amc_list_all'),
    path('upload-amc/', views.upload_amc, name='amc_upload_amc'),

]

clients/urls.py
from django.urls import path
from . import views
from .views import SupportRequestDeleteView, SupportRequestStatusUpdateView

urlpatterns = [
    path('', views.index, name='clients_index'),

    path('list/', views.ClientListView.as_view(), name='client_list'),
    path('create/', views.ClientCreateView.as_view(), name='client_create'),
    path('<pk>/update/', views.ClientEditView.as_view(), name='client_update'),
    path('<pk>/delete/', views.ClientDeleteView.as_view(), name='client_delete'),

    path('view_project/<pk>/', views.project, name="clients_view_project"),
    path('support_request/<pk>/', views.support_request, name="clients_view_support_request"),
    path('save_activity', views.save_activity, name='post_support_activity'),

    # View all clients of a project
    path('view_clients/<project_id>/', views.view_clients, name="projects_view_project_clients"),
    path('all_support_requests/', views.get_all_support_requests, name='clients_all_support_requests'),
    path('view_project/<client_project_id>/new_ticket/', views.new_ticket, name='clients_new_ticket'),

    # Client project urls
    path('client_projects_list/', views.ClientProjectsListView.as_view(), name='clients_projects_list'),
    path('client_project_create/', views.ClientProjectsCreateView.as_view(), name='clients_projects_create'),
    path('<pk>/client_project_update/', views.ClientProjectsEditView.as_view(), name='client_project_update'),

    path('<pk>/deleteTicket/', SupportRequestDeleteView.as_view(), name='delete_support_ticket'),
    path('<pk>/updateTicket', SupportRequestStatusUpdateView.as_view(), name='update_support_ticket'),

]

crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('home.urls')),
                  path('projects/', include('projects.urls')),
                  path('clients/', include('clients.urls')),
                  path('amc/', include('amc.urls')),
                  path('users/', include('users.urls')),
                  path('mail-box/', include('mail_box.urls')),


                  path('auth/', include('django.contrib.auth.urls')),
                  path('admin/', admin.site.urls),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
from datetime import datetime, timedelta

from ckeditor.fields import RichTextField
from crum import get_current_user
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models, connection
# Create your models here.
from django.utils import timezone

from my_lib.views import date_add_days, date_next_year


class Client(models.Model):
    class Meta:
        db_table = 'clients'
        verbose_name_plural = "Manage Clients"
        ordering = ['-id']

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    logo = models.ImageField(null=True, blank=True, upload_to='clients/', default='clients/client_default.png')
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True, related_name='+'
    )
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    @property
    def total_tickets(self):
        with connection.cursor() as cursor:
            query = "SELECT COUNT(*) total_tokens FROM support_requests sr " \
                    "LEFT JOIN client_projects cp ON cp.id=sr.client_project_id " \
                    "WHERE cp.client_id=" + str(self.id)

            cursor.execute(query)
            row = cursor.fetchone()

        return str(row[0])

    def save(self, *args, **kwargs):
        # print(self)
        # username = self.data.get('extra_field')
        self.created_by = get_current_user()
        super(Client, self).save(*args, **kwargs)
        if not self.code:
            # and self._state.adding:
            self.code = "C" + str(self.id)
            self.save()

    def __str__(self):
        return self.name


TOKEN_STATUS = (
    ('0', 'Active'),
    ('1', 'Due For AMC Renewal'),
    ('2', 'Project setup in progress'),
    ('3', 'Closed'),
)


class ClientProject(models.Model):
    class Meta:
        db_table = 'client_projects'
        verbose_name_plural = "Client Projects"
        ordering = ['-id']

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    project = models.ForeignKey("projects.Project", on_delete=models.CASCADE)
    start_date = models.DateField()
    next_amc_date = models.DateField(default=date_next_year)
    description = models.TextField()
    status = models.CharField(max_length=255, choices=TOKEN_STATUS, default='0')
    project_amount = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)
    amc_amount = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True
    )
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    @property
    def total_tickets(self):
        with connection.cursor() as cursor:
            query = "SELECT COUNT(*) total_tokens FROM support_requests sr " \
                    "LEFT JOIN client_projects cp ON cp.id=sr.client_project_id " \
                    "WHERE cp.id=" + str(self.id)

            cursor.execute(query)
            row = cursor.fetchone()

        return str(row[0])

    def save(self, *args, **kwargs):
        self.created_by = get_current_user()
        super(ClientProject, self).save(*args, **kwargs)

    def __str__(self):
        return self.client.name + " | " + self.project.name


class ClientProjectDocument(models.Model):
    class Meta:
        db_table = 'client_project_documents'
        verbose_name_plural = "Manage Client Project Documents"

    client_project = models.ForeignKey(ClientProject, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField()
    file = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True
    )
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    def save(self, *args, **kwargs):
        self.created_by = get_current_user()
        super(ClientProjectDocument, self).save(*args, **kwargs)


TICKET_STATUS = (
    ('0', 'Pending'),
    ('1', 'Open'),
    ('2', 'Awaiting Business Inputs'),
    ('3', 'With Client Review'),
    ('4', 'Closed|Resolved'),
    ('5', 'Deferred'),
)

TICKET_TYPES = (
    ('1', 'Service Related'),
    ('2', 'Sales Related'),
    ('3', 'Billing Related'),
    ('4', 'Others')
)


class SupportRequest(models.Model):
    class Meta:
        db_table = 'support_requests'
        verbose_name_plural = "Support Requests"
        ordering = ['-id']

    ticket_no = models.CharField(max_length=255)
    ticket_type = models.CharField(max_length=255, choices=TICKET_TYPES, default='1')
    client_project = models.ForeignKey(ClientProject, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    title = models.CharField(max_length=255, default='')
    description = models.TextField()
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True
    )

    status = models.CharField(max_length=255, choices=TICKET_STATUS, default='0')

    @property
    def created_by_logo(self):
        if self.created_by.is_staff:
            return "https://i.imgur.com/iNmBizf.jpg"

        else:
            return self.created_by.client.logo.url

    def save(self, *args, **kwargs):
        self.created_by = get_current_user()

        if not self.ticket_no:
            ticket_cnt = SupportRequest.objects.filter(client_project=self.client_project).count()
            project_code = self.client_project.project.code
            client_code = self.client_project.client.code

            self.ticket_no = "TICKET/" + project_code + "/" + client_code + "/" + str(ticket_cnt + 1)
            self.save()
        super(SupportRequest, self).save(*args, **kwargs)

    def __str__(self):
        return self.ticket_no


class SupportRequestFiles(models.Model):
    class Meta:
        db_table = 'support_request_files'
        verbose_name_plural = "Support Request Files"

    support_request = models.ForeignKey(SupportRequest, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(default=datetime.now, blank=True)
    file = models.FileField(null=True, blank=True, upload_to='TicketFiles/')


class SupportActivity(models.Model):
    class Meta:
        db_table = 'support_activities'
        verbose_name_plural = "Support Request Activities"

    support_request = models.ForeignKey(SupportRequest, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    description = models.TextField()
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True
    )

    @property
    def created_by_logo(self):
        if self.created_by.is_staff:
            return "https://i.imgur.com/iNmBizf.jpg"
        else:
            return self.created_by.client.logo.url

    def save(self, *args, **kwargs):
        self.created_by = get_current_user()
        super(SupportActivity, self).save(*args, **kwargs)


class SupportRequestActivityFiles(models.Model):
    class Meta:
        db_table = 'support_request_activity_files'
        verbose_name_plural = "Support Request Activity Files"

    activity = models.ForeignKey(SupportActivity, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(default=datetime.now, blank=True)
    file = models.FileField(null=True, blank=True, upload_to='TicketActivityFiles/')

clients/forms.py
from ckeditor.fields import RichTextField
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm, Textarea
from . import models
from .models import Client, ClientProject


class ClientForm(ModelForm):
    username = forms.CharField(label='Login Username')

    class Meta:
        model = models.Client
        fields = '__all__'
        exclude = ('created_at', 'created_by', 'user')
        widgets = {
            'address': forms.Textarea(attrs={'rows': 4, 'cols': 15}),
        }

    def clean_username(self):
        username = self.cleaned_data['username']
        if self.instance.pk is None:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError('duplicate username')
        return username

    def clean_code(self):
        code = self.cleaned_data['code']
        if self.instance.pk is None:
            if Client.objects.filter(code=code).exists():
                raise forms.ValidationError('duplicate client code')
        return code

    def save(self, commit=False):
        if self.instance.pk is None:
            username = self.cleaned_data['username']
            user = User.objects.create_user(
                username=username,
                first_name=self.cleaned_data['name'],
                is_staff=0,
                email=self.cleaned_data['email'],
                password='Daxis@217')
            self.instance.user = user

        return super(ClientForm, self).save(commit=True)

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields.pop('username', None)
            self.fields['code'].widget = forms.TextInput(attrs={'readonly': 'readonly'})

    # def __init__(self, *args, **kwargs):
    #     super(ClientForm, self).__init__(*args, **kwargs)
    #     for field in iter(self.fields):
    #         self.fields[field].widget.attrs.update({
    #             'class': 'form-control'
    #         })


class NewTicketForm(ModelForm):
    class Meta:
        model = models.SupportRequest
        fields = ('ticket_type', 'title', 'description', 'client_project')
        widgets = {
            'title': forms.TextInput(),
            'description': forms.Textarea(),
            'client_project': forms.HiddenInput(),
        }

    # def __init__(self, *args, **kwargs):
    #     super(NewTicketForm, self).__init__(*args, **kwargs)
    #     for field in iter(self.fields):
    #         self.fields[field].widget.attrs.update({
    #             'class': 'form-control'
    #         })


class SupportRequestFilesForm(forms.ModelForm):
    class Meta:
        model = models.SupportRequestFiles
        fields = ('file', 'support_request')


class ClientProjectsForm(ModelForm):
    class Meta:
        model = ClientProject
        fields = '__all__'
        exclude = ('created_at', 'created_by')

clients/templates/clients/client_confirm_delete.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block content %}

    <div class="row m-5" style="">

        <form method="post">{% csrf_token %}

            <p>Are you sure you want to delete "{{ object }}"?</p>

            <input type="submit" class="button btn btn-sm btn-danger" value="Confirm">
        </form>

    </div>

{% endblock content %}

clients/templates/clients/index.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block content %}

    <div style="text-align:left">
        <h4>All Clients</h4>
    </div>

    <hr>

{#    <div class="row col-md-4 ">#}
{#        <div class="input-group mb-3">#}
{#            <input type="text" class="form-control" placeholder="Search..." aria-label="Search..."#}
{#                   aria-describedby="basic-addon2">#}
{#            <div class="input-group-append">#}
{#                <button class="btn btn-outline-secondary" type="button">Button</button>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}


    <div class="row" style="">


        {% for client in clients %}


            <div class="card col-sm-4 mb-3">
                <div class="row ">
                    <div class="col-md-4 justify-content-center d-flex align-items-center">
                        <img src="{{ client.logo.url }}" class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ client.name }}</h5>
                            <p class="card-text">{{ client.email }}</p>
                            <p class="card-text">
                                <a href="{% url 'project_view_client_projects' client.id %}"
                                   class="btn btn-primary btn-sm">
                                    Show All Projects</a>
                            </p>
                        </div>

                    </div>

                    <ul class="list-group list-group-flush" style="border-top: 1px solid #ccc;">
                        <li class="list-group-item">
                            <span>Total Projects:
                                <span class="badge bg-info">{{ client.clientproject_set.all|length }}</span>
                                </span>
                            <span style="float: right">Total Tickets:
                                <span class="badge bg-success">{{ client.total_tickets }}</span>
                            </span>
                        </li>

                    </ul>

                </div>
            </div>

        {% empty %}
            <li>There are no clients</li>

        {% endfor %}

    </div>

{% endblock content %}

clients/templates/clients/new_support_request.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div style="text-align:left">
        <h4>Raise a new Ticket</h4>
    </div>

    <hr>

    <style>
        .ck-editor__editable_inline {
            min-height: 200px;
        }
    </style>
    <div class="row">

        <div class="alert alert-success" role="alert" style="display: none">

        </div>
        <div class="alert alert-danger" role="alert" style="display: none">

        </div>


        <form id="newTicketForm" method="post" enctype="multipart/form-data" action="" novalidate>

            {% csrf_token %}

            {{ form|crispy }}

            {#            <input type="hidden" name="client_project" value="{{ client_project_id }}">#}
            {##}
            {#            <div class="mb-3">#}
            {#                <label for="title" class="form-label">Please provide a title:</label>#}
            {#                <input type="text" name="title" class="form-control" id="title">#}
            {#                <div id="titleHelp" class="form-text">Brief a few about your ticket.</div>#}
            {#            </div>#}
            {#            <div class="mb-3">#}
            {#                <label for="description" class="form-label">Explain your issue here:</label>#}
            {#                <textarea class="form-control" name="description" id="description"></textarea>#}
            {#            </div>#}
            {##}
            <div class="mb-3">

                <label for="files" class="form-label">Upload Screenshots (Optional):</label>
                <input type="file" name="files" id="files" multiple>
            </div>

            <button type="submit" id="btn-submit" class="btn btn-primary btn-sm">Submit</button>
        </form>

    </div>

{% endblock content %}

{% block javascript %}

    <script src="https://cdn.ckeditor.com/ckeditor5/10.0.1/classic/ckeditor.js"></script>

    <script>
        ClassicEditor
            .create(document.querySelector('#id_description'), {
                removePlugins: [
                    'CKFinderUploadAdapter',
                    'CKFinder',
                    'EasyImage',
                    'Image',
                    'ImageCaption',
                    'ImageStyle',
                    'ImageToolbar',
                    'ImageUpload',
                    'MediaEmbed'],
            })
            .catch(error => {
                console.error(error);
            });
    </script>


    <script>


        $("form#newTicketForm").submit(function (e) {
            e.preventDefault();

            var this_btn = $("#btn-submit");
            this_btn.prop("disabled", true);

            var formData = new FormData(this);

            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: formData,
                success: function (data) {
                    this_btn.prop("disabled", false);

                    if (data.status === 'success') {

                        setTimeout(function () {
                            window.location.href = "/clients/support_request/" + data.id
                        }, 2000)

                        $('.alert-success').show().html(data.msg).delay(5000).fadeOut('slow');
                    } else {
                        $('.alert-danger').show().html(data.msg).delay(5000).fadeOut('slow');
                    }

                },
                cache: false,
                contentType: false,
                processData: false
            });
        });


    </script>





{% endblock javascript %}

clients/templates/clients/project_clients.html
{% extends 'base.html' %}

{% block content %}

    <div style="text-align:left">
        <h4>All Clients - {{ project_info.name }}</h4>
    </div>
    <hr>
    <div class="row">

        {% for data in project_client_data %}
            <div class="card col-sm-4 mb-3">
                <div class="row ">
                    <div class="col-md-4 justify-content-center d-flex align-items-center">
                        <img src="{{ data.client.logo.url|default_if_none:"https://axisproerp.com/images/axispro.png" }}"
                             class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ data.client.name }}</h5>
                            <p class="card-text">{{ data.client.email }}</p>
                            <p class="card-text">
                                <a href="{% url 'project_view_client_projects' data.client.id %}"
                                   class="btn btn-primary btn-sm">
                                    Show All Projects</a>
                            </p>
                        </div>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <span>Total Projects:
                                <span class="badge bg-info">{{ data.client.clientproject_set.all|length }}</span>
                            </span>
                            <span style="float: right">Total Tickets:
                                <span class="badge bg-success">{{ data.total_tickets }}</span>
                            </span>

                        </li>
                    </ul>
                </div>
            </div>


        {% empty %}
            <li>There are no clients assigned for any project</li>

        {% endfor %}

    </div>

{% endblock content %}

clients/templates/clients/support_request.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block content %}
    <style>

        .img-sm {
            width: 46px;
            height: 46px;
        }

        .mar-top {
            margin-top: 15px;
        }


    </style>

    <div style="text-align:center">
        <h4>Support Ticket No - # {{ support_request_data.ticket_no }} </h4>
    </div>

    <div class="alert alert-success" role="alert" style="display: none">

    </div>
    <div class="alert alert-danger" role="alert" style="display: none">

    </div>


    <div class="container-fluid mt-100">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-header">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img style="width: 65px;" src="{{ support_request_data.created_by_logo }}"
                                 class="d-block ui-w-40 rounded-circle"
                                 alt="">

                            <div class="row">

                                <div class="media-body ml-3 col-md-9">
                                    <a href="javascript:void(0)" data-abc="true">
                                        {{ support_request_data.created_by.first_name }}
                                        {{ support_request_data.created_by.last_name }}
                                    </a>
                                    <div class="text-muted small">
                                        {{ support_request_data.created_at | timesince }} ago
                                    </div>
                                    <div class="text-muted small">
                                        Status : {{ support_request_data.get_status_display }}
                                    </div>
                                </div>
                                <div class="text-muted small ml-3 col-md-3" style="float:right">
                                    <div>Member since <strong>
                                        {{ support_request_data.created_by.date_joined | date }}
                                    </strong></div>
                                    <div>Total of <strong>{{ user_total_service_requests }}</strong> service requests has been created by you</div>
                                </div>

                            </div>

                        </div>
                    </div>
                    <div class="card-body">
                        <p> {{ support_request_data.description|safe }} </p>
                    </div>

                    {% if support_request_data.supportrequestfiles_set.all %}

                        <div class="card-footer">

                            {% for f in support_request_data.supportrequestfiles_set.all %}
                                <a target="_blank" class="activity_file_link" href="{{ f.file.url }}"
                                   style="margin-right: 15px">
                                    File-{{ forloop.counter }}
                                </a>
                            {% endfor %}

                        </div>

                    {% endif %}


                </div>
            </div>
        </div>


    </div>

    <div class="container bootdey">
        <div class="col-md-12 bootstrap snippets">
            <div class="panel">
                <div class="panel-body">

                    <form id="posting-form">
                        <input type="hidden" id="support_request_id" value="{{ support_request_data.id }}">
                        <textarea id="description" class="form-control" rows="2"
                                  placeholder="Please type here"></textarea>
                        <div class="mar-top clearfix">
                            <button id="btn-post-activity"
                                    class="btn btn-sm btn-primary pull-right" type="button">
                                <i class="fa fa-pencil fa-fw"></i>
                                Post
                            </button>

                            <div class="file-path-wrapper">
                                <input type="file" name="file" id="file" multiple>
                            </div>

                        </div>

                    </form>


                </div>
            </div>
            <div class="panel">
                <div class="panel-body">
                    <!-- Newsfeed Content -->
                    <!--===================================================-->
                    <div class="media-block">
                        <div class="media-body">

                            <hr>
                            <!-- Comments -->


                            {% for activity in support_activity_data %}


                                <div>
                                    <div class="media-block">
                                        <a class="media-left" href="#">
                                            <img class="img-circle img-sm" alt="Profile Picture"
                                                 src="{{ activity.created_by_logo }}"></a>
                                        <div class="media-body">
                                            <div class="mar-btm">
                                                <a href="#" class="btn-link text-semibold media-heading box-inline">
                                                    {{ activity.created_by.first_name }}
                                                </a>
                                                <p class="text-muted text-sm"><i class="fa fa-clock-o fa-lg"></i>
                                                    {{ activity.created_at | timesince }} ago
                                                </p>

                                            </div>
                                            <p>{{ activity.description }}</p>

                                            <p>

                                                {% for f in activity.supportrequestactivityfiles_set.all %}
                                                    <a target="_blank" class="activity_file_link"
                                                       href="{{ f.file.url }}"
                                                       style="margin-right: 15px">
                                                        File-{{ forloop.counter }}
                                                    </a>
                                                {% endfor %}

                                            </p>

                                            <hr>
                                        </div>


                                    </div>

                                    {#                                </div>#}
                                </div>
                            {% endfor %}


                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}


{% block javascript %}

    <script>

        $("#btn-post-activity").click(function () {

            var this_btn = $(this);
            this_btn.prop("disabled", true);

            var description = $("#description").val();
            var request_id = $("#support_request_id").val();

            var form_data = new FormData();
            $.each($("#file")[0].files, function (i, file) {
                form_data.append("file", file);
            });

            form_data.append("description", description)
            form_data.append("request_id", request_id)
            form_data.append("csrfmiddlewaretoken", "{{ csrf_token }}")

            $.ajax({
                url: "{% url 'post_support_activity' %}",
                dataType: 'json',
                cache: false,
                contentType: false,
                processData: false,
                data: form_data,
                type: 'POST',

                success: function (data) {

                    this_btn.prop("disabled", false);

                    if (data.status === 'success')
                        $('.alert-success').show().html(data.msg).delay(5000).fadeOut('slow');
                    else
                        $('.alert-danger').show().html(data.msg).delay(5000).fadeOut('slow');

                    setTimeout(function () {
                        location.reload()
                    }, 2000)
                },

                failure: function () {
                    $('.alert-danger').show().html("Something went wrong. Please try again").delay(5000).fadeOut('slow');
                }


            });

        })

    </script>

{% endblock javascript %}