amc/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('create/', views.AmcCreateView.as_view(), name='amc_create'),
    path('<pk>/update/', views.AmcEditView.as_view(), name='amc_update'),
    path('<pk>/delete/', views.AmcDeleteView.as_view(), name='amc_delete'),

    path('list/', views.get_all_amc, name='amc_list_all'),
    path('upload-amc/', views.upload_amc, name='amc_upload_amc'),

]

crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('home.urls')),
                  path('projects/', include('projects.urls')),
                  path('clients/', include('clients.urls')),
                  path('amc/', include('amc.urls')),
                  path('users/', include('users.urls')),
                  path('mail-box/', include('mail_box.urls')),


                  path('auth/', include('django.contrib.auth.urls')),
                  path('admin/', admin.site.urls),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='projects_index'),

    path('list/', views.ProjectListView.as_view(), name='project_list'),
    path('create/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<pk>/update/', views.ProjectEditView.as_view(), name='project_update'),
    path('<pk>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),

    # View all projects of a client
    path('view_projects/<client_id>/', views.client_projects, name='project_view_client_projects'),
]

clients/models.py
from datetime import datetime, timedelta

from ckeditor.fields import RichTextField
from crum import get_current_user
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models, connection
# Create your models here.
from django.utils import timezone

from my_lib.views import date_add_days, date_next_year


class Client(models.Model):
    class Meta:
        db_table = 'clients'
        verbose_name_plural = "Manage Clients"
        ordering = ['-id']

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    logo = models.ImageField(null=True, blank=True, upload_to='clients/', default='clients/client_default.png')
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True, related_name='+'
    )
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    @property
    def total_tickets(self):
        with connection.cursor() as cursor:
            query = "SELECT COUNT(*) total_tokens FROM support_requests sr " \
                    "LEFT JOIN client_projects cp ON cp.id=sr.client_project_id " \
                    "WHERE cp.client_id=" + str(self.id)

            cursor.execute(query)
            row = cursor.fetchone()

        return str(row[0])

    def save(self, *args, **kwargs):
        # print(self)
        # username = self.data.get('extra_field')
        self.created_by = get_current_user()
        super(Client, self).save(*args, **kwargs)
        if not self.code:
            # and self._state.adding:
            self.code = "C" + str(self.id)
            self.save()

    def __str__(self):
        return self.name


TOKEN_STATUS = (
    ('0', 'Active'),
    ('1', 'Due For AMC Renewal'),
    ('2', 'Project setup in progress'),
    ('3', 'Closed'),
)


class ClientProject(models.Model):
    class Meta:
        db_table = 'client_projects'
        verbose_name_plural = "Client Projects"
        ordering = ['-id']

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    project = models.ForeignKey("projects.Project", on_delete=models.CASCADE)
    start_date = models.DateField()
    next_amc_date = models.DateField(default=date_next_year)
    description = models.TextField()
    status = models.CharField(max_length=255, choices=TOKEN_STATUS, default='0')
    project_amount = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)
    amc_amount = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True
    )
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    @property
    def total_tickets(self):
        with connection.cursor() as cursor:
            query = "SELECT COUNT(*) total_tokens FROM support_requests sr " \
                    "LEFT JOIN client_projects cp ON cp.id=sr.client_project_id " \
                    "WHERE cp.id=" + str(self.id)

            cursor.execute(query)
            row = cursor.fetchone()

        return str(row[0])

    def save(self, *args, **kwargs):
        self.created_by = get_current_user()
        super(ClientProject, self).save(*args, **kwargs)

    def __str__(self):
        return self.client.name + " | " + self.project.name


class ClientProjectDocument(models.Model):
    class Meta:
        db_table = 'client_project_documents'
        verbose_name_plural = "Manage Client Project Documents"

    client_project = models.ForeignKey(ClientProject, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField()
    file = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True
    )
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    def save(self, *args, **kwargs):
        self.created_by = get_current_user()
        super(ClientProjectDocument, self).save(*args, **kwargs)


TICKET_STATUS = (
    ('0', 'Pending'),
    ('1', 'Open'),
    ('2', 'Awaiting Business Inputs'),
    ('3', 'With Client Review'),
    ('4', 'Closed|Resolved'),
    ('5', 'Deferred'),
)

TICKET_TYPES = (
    ('1', 'Service Related'),
    ('2', 'Sales Related'),
    ('3', 'Billing Related'),
    ('4', 'Others')
)


class SupportRequest(models.Model):
    class Meta:
        db_table = 'support_requests'
        verbose_name_plural = "Support Requests"
        ordering = ['-id']

    ticket_no = models.CharField(max_length=255)
    ticket_type = models.CharField(max_length=255, choices=TICKET_TYPES, default='1')
    client_project = models.ForeignKey(ClientProject, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    title = models.CharField(max_length=255, default='')
    description = models.TextField()
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True
    )

    status = models.CharField(max_length=255, choices=TICKET_STATUS, default='0')

    @property
    def created_by_logo(self):
        if self.created_by.is_staff:
            return "https://i.imgur.com/iNmBizf.jpg"

        else:
            return self.created_by.client.logo.url

    def save(self, *args, **kwargs):
        self.created_by = get_current_user()

        if not self.ticket_no:
            ticket_cnt = SupportRequest.objects.filter(client_project=self.client_project).count()
            project_code = self.client_project.project.code
            client_code = self.client_project.client.code

            self.ticket_no = "TICKET/" + project_code + "/" + client_code + "/" + str(ticket_cnt + 1)
            self.save()
        super(SupportRequest, self).save(*args, **kwargs)

    def __str__(self):
        return self.ticket_no


class SupportRequestFiles(models.Model):
    class Meta:
        db_table = 'support_request_files'
        verbose_name_plural = "Support Request Files"

    support_request = models.ForeignKey(SupportRequest, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(default=datetime.now, blank=True)
    file = models.FileField(null=True, blank=True, upload_to='TicketFiles/')


class SupportActivity(models.Model):
    class Meta:
        db_table = 'support_activities'
        verbose_name_plural = "Support Request Activities"

    support_request = models.ForeignKey(SupportRequest, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    description = models.TextField()
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True
    )

    @property
    def created_by_logo(self):
        if self.created_by.is_staff:
            return "https://i.imgur.com/iNmBizf.jpg"
        else:
            return self.created_by.client.logo.url

    def save(self, *args, **kwargs):
        self.created_by = get_current_user()
        super(SupportActivity, self).save(*args, **kwargs)


class SupportRequestActivityFiles(models.Model):
    class Meta:
        db_table = 'support_request_activity_files'
        verbose_name_plural = "Support Request Activity Files"

    activity = models.ForeignKey(SupportActivity, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(default=datetime.now, blank=True)
    file = models.FileField(null=True, blank=True, upload_to='TicketActivityFiles/')

projects/models.py
from crum import get_current_user
from django.conf import settings
from django.db import models

# Create your models here.
from django.utils.datetime_safe import datetime


class Project(models.Model):
    class Meta:
        db_table = 'projects'
        verbose_name_plural = "Manage Projects"
        ordering = ['-id']

    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField()
    logo = models.FileField(null=True, blank=True, upload_to='projects/', default='projects/project_default.png')
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True
    )
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    def save(self, *args, **kwargs):
        self.created_by = get_current_user()
        super(Project, self).save(*args, **kwargs)

        if not self.code:
            self.code = "P" + str(self.id)
            self.save()

    def __str__(self):
        return self.name

projects/forms.py
from django import forms
from django.forms import ModelForm

from .models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        exclude = ('created_at', 'created_by')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4, 'cols': 15}),
        }

    def clean_code(self):
        code = self.cleaned_data['code']
        if self.instance.pk is None:
            if Project.objects.filter(code=code).exists():
                raise forms.ValidationError('duplicate code')
        return code

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields['code'].widget = forms.TextInput(attrs={'readonly': 'readonly'})

projects/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, DeleteView, ListView

from clients.models import ClientProject, Client
from my_lib.decorators import class_view_decorator
from .forms import ProjectForm
from .models import Project


# Create your views here.
@login_required
@staff_member_required
def index(request):
    projects = Project.objects.all()
    return render(request, 'projects/index.html', {'projects': projects})


# View list of all projects of client
@login_required
@staff_member_required
def client_projects(request, client_id):
    client_info = get_client_info(client_id)
    client_projects_data = get_client_projects(client_id)

    data = {"client_projects_data": client_projects_data, "client_info": client_info}
    return render(request, 'projects/client_projects.html', data)


def client_dashboard(request):
    client = request.user.client
    if client is not None:
        client_id = client.id
        client_info = get_client_info(client_id)
        client_projects_data = get_client_projects(client_id)

        data = {"client_projects_data": client_projects_data, "client_info": client_info}
        return render(request, 'projects/client_projects.html', data)


def get_client_projects(client_id):
    client_projects_data = ClientProject.objects.filter(client_id=client_id)
    return client_projects_data


def get_client_info(client_id):
    client_info = Client.objects.get(pk=client_id)
    return client_info


@class_view_decorator(staff_member_required)
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'common/basic-form.html'
    success_url = reverse_lazy('projects_index')
    extra_context = {'page_head': "New Project"}


@class_view_decorator(staff_member_required)
class ProjectEditView(UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'common/basic-form.html'
    success_url = reverse_lazy('projects_index')
    extra_context = {'page_head': "Edit Project"}


@class_view_decorator(staff_member_required)
class ProjectDeleteView(DeleteView):
    model = Project
    success_url = reverse_lazy('clients_index')


@class_view_decorator(staff_member_required)
class ProjectListView(ListView):
    model = Project
    template_name = 'projects/list.html'
    paginate_by = 10

projects/templates/projects/client_projects.html
{% extends 'base.html' %}

{% block content %}

    <style>

        .card-img-div {
            border-bottom: 1px solid #dedcdc;
        }

    </style>

    <div style="text-align:left">
        <h4>All Projects - {{ client_info.name }}</h4>
    </div>
    <hr>

    <div class="row ">


        {% for data in client_projects_data %}



            <div class="card col-md-3" style="height: 415px; ">
                <div class="text-center mt-2 card-img-div" style="height: 60px">
                    <img style="width: 200px; max-height: 60px;text-align: center" src="{{ data.project.logo.url }}"
                         class="card-img-top"
                         alt="...">

                </div>
                <div class="card-body">
                    <h5 class="card-title text-center">{{ data.project.name }}</h5>
                    <p class="card-text text-center">{{ data.project.description|truncatechars:100 }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item text-center">Start Date : {{ data.start_date }}</li>
                    <li class="list-group-item text-center">Next AMC : {{ data.next_amc_date }}</li>
                    <li class="list-group-item text-center">
                        Total Tickets :
                    <span class="badge bg-success">{{ data.supportrequest_set.all|length }}</span>
                    </li>
                    <li class="list-group-item text-center">
                        <a href="{% url 'clients_view_project' data.id %}" class="btn btn-primary btn-sm m-1">
                            View Project</a>
                        <a href="{% url 'clients_new_ticket' data.id %}" class="btn btn-google btn-sm m-1">
                            New Ticket</a>
                    </li>

                </ul>
            </div>

        {% empty %}
            <li>There are no projects assigned for this client</li>

        {% endfor %}

    </div>

{% endblock content %}

projects/templates/projects/index.html
{% extends 'base.html' %}

{% block content %}

    <style>

        .card-img-div {
            border-bottom: 1px solid #dedcdc;
        }

    </style>

    <div style="text-align:left">
        <h4>All Projects</h4>
    </div>
    <hr>
    <div class="row ">

        {% for project in projects %}
            <div class="card col-md-3" style="height: 319px; ">
                <div class="text-center mt-2 card-img-div" style="height: 60px">
                    <img style="width: 200px; max-height: 60px;text-align: center" src="{{ project.logo.url }}"
                         class="card-img-top"
                         alt="...">

                </div>
                <div class="card-body">
                    <h5 class="card-title text-center">{{ project.name }}</h5>
                    <p class="card-text text-center">{{ project.description|truncatechars:100 }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item text-center">
                        Total Clients:
                        <span class="badge bg-success">{{ project.clientproject_set.all|length }}</span>
                    </li>
                    <li class="list-group-item text-center">
                        <a href="{% url 'projects_view_project_clients' project.id %}" class="btn btn-primary btn-sm">Show
                            Clients</a></li>
                </ul>
            </div>

        {% empty %}
            <li>There are no projects</li>

        {% endfor %}

    </div>

{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block content %}


    <style>
        .dropdown-toggle {
            width: 100%;
        }

    </style>


    <div style="text-align:left">
        <h4>All Projects <a href="{% url 'project_create' %}" class="btn btn-md btn-facebook">Create</a></h4>
    </div>
    <hr>

    <div class="row">


        <div class="row justify-content-center d-flex align-items-center text-center">


            <table class="table table-sm table-responsive">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Code</th>
                    <th scope="col" style="width: 25%">Description</th>
                    <th scope="col">Logo</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>

                {% for obj in object_list %}
                    <tr class="text-center">
                        <th scope="row" class="align-middle">{{ forloop.counter }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.code }}</td>
                        <td>{{ obj.description|truncatechars:75 }}</td>
                        <td><img src="{{ obj.logo.url }}" style="width: 175px"></td>
                        <td>

                            <div class="row justify-content-center d-flex align-items-center">

                                <div class="dropdown">
                                    <button class="btn btn-google btn-sm dropdown-toggle" type="button"
                                            id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                        Action
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                        <li><a class="dropdown-item"
                                               href="{% url 'project_update' obj.id %}">Edit</a></li>
                                        <li><a class="dropdown-item"
                                               href="{% url 'project_delete' obj.id %}">Delete</a></li>
                                    </ul>
                                </div>

                            </div>


                        </td>

                    </tr>

                {% empty %}
                    <tr>
                        <td colspan="5">There are no clients</td>
                    </tr>

                {% endfor %}

                </tbody>
            </table>


             <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                    {% endif %}

                    {% if page_obj.number|add:'-4' > 1 %}
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
                    {% endif %}

                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active" aria-current="page">
                              <span class="page-link">
                                {{ i }}
                              </span>
                            </li>
                        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                        <li class="page-item"><a class="page-link" href="?page={{ data.number|add:'5' }}">&hellip;</a>
                        </li>
                    {% endif %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>

        </div>
    </div>




{% endblock content %}


{% block javascript %}

    <script>

        $(function () {
            $(".datepicker").datepicker({
                autoclose: true,
                todayHighlight: true
            })
        });

    </script>


    <script>


        $(document).on("click", ".delete-req", function (e) {

            e.preventDefault();
            var url = $(this).attr("href")

            $.ajax({
                url: url,
                dataType: 'json',
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                type: 'post',

                success: function (data) {
                    alert(data.msg);
                    location.reload()
                }
            })

        });


        $(document).on("click", ".ticket_status", function (e) {

            e.preventDefault();
            var url = $(this).attr("href")
            var status = $(this).data("status")

            $.ajax({
                url: url,
                dataType: 'json',
                data: {
                    status: status,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                type: 'post',

                success: function (data) {
                    alert(data.msg);
                    location.reload()
                }
            })

        });


    </script>



{% endblock javascript %}